site_name: cacheStore
site_description: Documentation for cacheStore
site_author: DeathToTheStadium
site_url: https://deathtothestadium.github.io/cacheStore/

nav:
  - Home: index.md

theme:
  name: material